name: Build Branch

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout sources"
        uses: actions/checkout@v2

      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: "Build"
        run: chmod 755 mvnw && ./mvnw install

      - name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.SIGNING_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Set up Git user
        run: |
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name ${{ secrets.GH_USERNAME }}

      # Publishes to Artifactory only on push to the "release" branch.
      - name: "Publish"
        if: github.ref == 'refs/heads/release'
        run: |
          chmod 755 mvnw
          export GPG_TTY=$(tty)
          ./mvnw -Dusername=${{ secrets.GH_USERNAME }} -Dpassword=${{ secrets.GH_ACCESS_TOKEN }} release:prepare
          ./mvnw -Darguments="-Dgpg.passphrase=${{ secrets.SIGNING_PASSWORD }}" -Dusername=${{ secrets.ARTIFACTORY_USER }} -Dpassword=${{ ARTIFACTORY_PASSWORD }} release:perform -Pdeploy